#version: '3.8'
#
#services:
#  auth-service:
#    image: auth-service:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ConnectionStrings__AuthDbConnection="Host=studenthousing-1678.jxf.gcp-europe-west1.cockroachlabs.cloud;Database=AuthDb;Username=timothyaxell;Password=Hbz-pgWXVPjUGPIU3HDGVA;Port=26257;SslMode=VerifyFull"
#    networks:
#      - backend-network
#
#networks:
#  backend-network:
#    driver: bridge
